# Generated by Django 5.2.5 on 2025-08-22 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('parent_pid', models.IntegerField()),
                ('cpu_percent', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('disk_usage', models.FloatField(default=0.0)),
                ('net_usage', models.FloatField(default=0.0)),
            ],
            options={
                'indexes': [models.Index(fields=['hostname', 'timestamp'], name='processes_p_hostnam_5255f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('hostname', models.CharField(default='Unknown', max_length=255)),
                ('operating_system', models.CharField(default='Unknown', max_length=255)),
                ('processor', models.CharField(default='Unknown', max_length=255)),
                ('number_of_cores', models.IntegerField(default=0)),
                ('number_of_threads', models.IntegerField(default=0)),
                ('ram_gb', models.FloatField(default=0.0)),
                ('used_ram_gb', models.FloatField(default=0.0)),
                ('available_ram_gb', models.FloatField(default=0.0)),
                ('storage_total_gb', models.FloatField(default=0.0)),
                ('storage_used_gb', models.FloatField(default=0.0)),
                ('storage_free_gb', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['hostname', 'updated_at'], name='processes_s_hostnam_477124_idx')],
            },
        ),
    ]
